server:
  port: 8081
  #  加上前缀，方便前端做映射处理
#  servlet:
#    context-path: /lja
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&useSSL=false&
          serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 5
      min-idle: 5
      initial-size: 5
      max-total: 10
      #max-wait-millis: 150
      max-wait-millis: 10000
      min-evictable-idle-time-millis: 3000
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 3000

mybatis:
  # mybatis配置实体类的路径
  type-aliases-package: com.lja.domian
  # mybatis配置mapper.xml路径
  mapper-locations: classpath*:/mappers/*.xml
  # mybatis全局配置的路径
  config-location: classpath:/mybatis-config/mybatis-config.xml