server:
  port: 8081
  #  加上前缀，方便前端做映射处理
#  servlet:
#    context-path: /lja
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true&useSSL=false&
          serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 5
      min-idle: 5
      initial-size: 5
      max-total: 10
      #max-wait-millis: 150
      max-wait-millis: 10000
      min-evictable-idle-time-millis: 3000
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 3000
#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
#    password: # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制

mybatis:
  # mybatis配置实体类的路径
  type-aliases-package: com.lja.infrastructure.domain
  # mybatis配置mapper.xml路径
  mapper-locations: classpath*:/mappers/*.xml
  # mybatis全局配置的路径
  config-location: classpath:/mybatis-config/mybatis-config.xml


